config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  concern :searchable do
    post 'search_entries/index'
  end

  post 'search_entries/index'
  resources :shopping_lists
  resources :food_consumption_events, except: :show
  resources :meal_consumption_events, except: :show
  devise_for :users
  resources :meals do
    resources :ingredients
  end
  namespace :foods do
    concerns :searchable
  end

  post "foods/filter", to: 'foods#filter', as: "foods_filter"
  post "meals/filter", to: 'meals#filter', as: "meals_filter"
  namespace :meals do
    concerns :searchable
  end
  resources :foods
  get 'user_targets', to: 'user_targets#show', as: :user_targets
  patch 'user_targets', to: 'user_targets#update'
  get 'user_targets/edit', to: 'user_targets#edit', as: :edit_user_targets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'daily_log#index', as: :daily_log
end

app/models/ingredient.rb
# frozen_string_literal: true
class Ingredient < ApplicationRecord

  include Edible
  belongs_to :meal
  belongs_to :food

  has_one :macros, class_name: 'IngredientMacros'

  scope :with_food, ->(food) { where(food: food) }

end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true
class IngredientsController < ApplicationController

  before_action :set_ingredient, only: %i[show edit update destroy]
  before_action :set_meal

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show; end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit; end

  # POST /ingredients or /ingredients.json
  def create
    if existing_ingredient_for_food(food)
      @ingredient = existing_ingredient_for_food(food)
      @ingredient.grams += ingredient_params[:grams].to_f
      broadcast = Broadcasts::UpdateIngredient
    else
      @ingredient = @meal.ingredients.new(ingredient_params)
      broadcast = Broadcasts::CreateIngredient
    end

    respond_to do |format|
      if @ingredient.save
        broadcast.perform(ingredient: @ingredient)
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(
            'new_ingredient',
            partial: 'ingredients/form',
            locals: {
              ingredient: @meal.ingredients.new,
              notice: 'Ingredient was successfully created.'
            }
          )
        end
        format.html { redirect_to meal_ingredient_url(@ingredient), notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to meal_url(@meal), notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    Broadcasts::DestroyIngredient.perform(ingredient: @ingredient)
    respond_to do |format|
      format.html { redirect_to meal_url(@meal), notice: 'Ingredient was successfully destroyed.' }
      format.turbo_stream do
        head :no_content, status: :ok
      end
      format.json { head :no_content }
    end
  end

  private

  def existing_ingredient_for_food(food)
    @meal.ingredients.with_food(food).last
  end

  def food
    @food ||= Food.find(ingredient_params[:food_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def set_meal
    @meal = Meal.find(params[:meal_id])
  end

  def broadcast_update_ingredient_table
    lambda {
      @ingredient
        .broadcast_replace_to(
          :ingredient_rows,
          target: @ingredient,
          partial: 'edibles/row',
          locals: { edible: @ingredient }
        )
    }
  end

  # Only allow a list of trusted parameters through.
  def ingredient_params
    params.require(:ingredient).permit(:food_id, :grams)
  end

end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<% url = ingredient.new_record? ? meal_ingredients_path(meal_id: @meal.id) : meal_ingredient_path(ingredient, meal_id: @meal.id) %>
<%= form_with(url: url, model: ingredient, class: "contents") do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if ingredient.new_record? %>
    <div class="my-5">
      <%= form.select :food_id, options_from_collection_for_select(Food.all, :id, :name, ingredient.food_id) %>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :grams %>
    <%= form.text_field :grams, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Meal:</strong>
    <%= ingredient.meal_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Food:</strong>
    <%= ingredient.food_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Grams:</strong>
    <%= ingredient.grams %>
  </p>

    <%= link_to 'Edit this ingredient', edit_meal_ingredient_path(ingredient), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
</div>

app/views/ingredients/_ingredient_row.html.erb
<% present(ingredient) do |present_ingredient| %>
  <tr id=<%= dom_id(ingredient) %>>
    <td class="px-7">
      <%= present_ingredient.name %>
    </td>

    <td class="px-7">
      <%= present_ingredient.grams %>
    </td>

    <td class="px-7">
      <%= present_ingredient.fat %>
    </td>

    <td class="px-7">
      <%= present_ingredient.carbs %>
    </td>

    <td class="px-7">
      <%= present_ingredient.fibre %>
    </td>

    <td class="px-7">
      <%= present_ingredient.protein %>
    </td>

    <td class="px-7">
      <%= present_ingredient.calories %>
    </td>

    <td>
      <%= link_to 'Edit', present_ingredient.edit_path, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    </td>
  </tr>
<% end %>

app/views/ingredients/_table.html.erb
<table class="min-w-full divide-y divide-gray-200">
  <thead class="bg-gray-50">
    <tr>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
        Food
      </th>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
        Grams
      </th>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
        Fat
      </th>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
        Carbs
      </th>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
        Fibre
      </th>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
        Protein
      </th>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
        Calories
      </th>
      <th scope="col" class="relative px-6 py-3">
        <span class="sr-only">Edit</span>
      </th>
    </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200" id="ingredient_rows">
    <%= turbo_stream_from :ingredient_rows %>
    <% edibles.each do |ingredient|%>
      <%= render partial: "ingredients/ingredient_row", locals: {ingredient: ingredient} %>
    <% end %>
  </tbody>
</table>

app/views/ingredients/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing amount of <%= @ingredient.food.name %></h1>

  <%= render "form", ingredient: @ingredient %>
  <%= link_to "Back to meal", meal_path(@ingredient.meal), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ingredients/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ingredients</h1>
    <%= link_to 'New ingredient', new_ingredient_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="ingredients" class="min-w-full">
    <%= render @ingredients %>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ingredient</h1>

  <%= render "form", ingredient: @ingredient %>

  <%= link_to 'Back to ingredients', ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ingredients/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ingredient %>

    <%= link_to 'Edit this ingredient', edit_meal_ingredient_path(@ingredient), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this ingredient', meal_ingredient_path(@ingredient), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to Meal', meal_path(@ingredient.meal), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>