config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  concern :searchable do
    post 'search_entries/index'
  end

  post 'search_entries/index'
  resources :shopping_lists
  resources :food_consumption_events, except: :show
  resources :meal_consumption_events, except: :show
  devise_for :users
  resources :meals do
    resources :ingredients
  end
  namespace :foods do
    concerns :searchable
  end

  post "foods/filter", to: 'foods#filter', as: "foods_filter"
  post "meals/filter", to: 'meals#filter', as: "meals_filter"
  namespace :meals do
    concerns :searchable
  end
  resources :foods
  get 'user_targets', to: 'user_targets#show', as: :user_targets
  patch 'user_targets', to: 'user_targets#update'
  get 'user_targets/edit', to: 'user_targets#edit', as: :edit_user_targets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'daily_log#index', as: :daily_log
end

app/models/meal.rb
# frozen_string_literal: true
class Meal < ApplicationRecord

  include Edible
  include Searchable

  has_many :ingredients

  %i[fat fibre carbs protein calories].each do |macro|
    define_method(macro) do
      ingredients.includes(:macros).sum { |ingredient| ingredient.macros.send(macro) }
    end
  end

end

app/controllers/meals/search_entries_controller.rb
# frozen_string_literal: true

module Meals
  class SearchEntriesController < SearchEntriesController

    private

    def query
      super.search_only_in_model(Meal)
    end

  end
end

app/controllers/meals_controller.rb
# frozen_string_literal: true
class MealsController < ApplicationController

  before_action :set_meal, only: %i[show edit update destroy]

  # GET /meals or /meals.json
  def index
    @meals = Meal.all
  end

  def filter
    query = SearchQuery.new(params[:search])
    query.search_only_in_model(Meal)
    search = Search::PerformSearchCommand.perform(search_query: query)
    @meals = if search.success?
              Meal.where(id: search.value!.select(:searchable_id))
            else
              Meal.all.order('created_at desc')
            end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
                 "meals", partial: "meals/meals", locals: {meals: @meals }
               )
      end
    end
  end

  # GET /meals/1 or /meals/1.json
  def show; end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit; end

  # POST /meals or /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        Search::CreateSearchEntryCommand.perform(searchable_object: @meal)
        format.html { redirect_to meal_url(@meal), notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1 or /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        Search::UpdateSearchEntryCommand.perform(searchable_object: @meal)
        format.html { redirect_to meal_url(@meal), notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1 or /meals/1.json
  def destroy
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meal
    @meal = Meal.includes(ingredients: :food).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meal_params
    params.require(:meal).permit(:name, :recipe)
  end

end

app/helpers/meals_helper.rb
# frozen_string_literal: true
module MealsHelper
end

app/views/meals/_form.html.erb
<%= form_with(model: meal, class: "contents") do |form| %>
  <% if meal.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
        <% meal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :recipe %>
    <%= form.text_field :recipe, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/meals/_ingredients_table.html.erb
<div class="mx-auto">
  <%= render partial: "edibles/table", locals: {
         edibles: @meal.ingredients,
         turbo_stream_to_subscribe_to: :ingredient_rows
       }
  %>

<%= render "search_entries/search_bar", search_url: foods_search_entries_index_url, parent_item: @meal %>
</div>

app/views/meals/_macros.html.erb
<table class="min-w-full table-auto divide-y divide-gray-200">
  <thead class="bg-gray-50">
    <tr>
      <th scope="col" class="w-1/5">
        <p class="ml-2 text-left">Fat</p>
      </th>
      <th scope="col" class="w-1/5">
        <p class="ml-2 text-left">Carbs</p>
      </th>
      <th scope="col" class="w-1/5">
        <p class="ml-2 text-left">Protein</p>
      </th>
      <th scope="col" class="w-1/5">
        <p class="ml-2 text-left">Fibre</p>
      </th>
      <th scope="col" class="w-1/5">
        <p class="ml-2 text-left">Calories</p>
      </th>
    </tr>
  </thead>
  <% present(meal) do |present_meal| %>
  <tbody>
    <tr>
      <td>
        <p class="ml-2 text-left"><%= present_meal.fat %></p>
      </td>
      <td>
        <p class="ml-2 text-left"><%= present_meal.carbs %></p>
      </td>
      <td>
        <p class="ml-2 text-left"><%= present_meal.protein %></p>
      </td>
      <td>
        <p class="ml-2 text-left"><%= present_meal.fibre %></p>
      </td>
      <td>
        <p class="ml-2 text-left"><%= present_meal.calories %></p>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/meals/_meal.html.erb
<div id="<%= dom_id meal %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= meal.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Recipe:</strong>
    <%= meal.recipe %>
  </p>

  <%= render "macros", meal: meal %>

  <% if action_name != "show" %>
    <%= link_to "Show this meal", meal, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this meal', edit_meal_path(meal), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/meals/_meals.html.erb
  <div id="meals" class="min-w-full">
    <%= render meals %>
  </div>

app/views/meals/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing meal</h1>

  <%= render "form", meal: @meal %>

  <%= link_to "Show this meal", @meal, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to meals", meals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/meals/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Meals</h1>
    <%= link_to 'New meal', new_meal_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
<%= turbo_frame_tag "meals_filter" do %>
    <%= form_with url: meals_filter_url do |form| %>
      <%= form.text_field :search %>
      <%= form.button("Search") %>
    <% end %>

    <%= render "meals", meals: @meals %>
    <% end %>
</div>

app/views/meals/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New meal</h1>

  <%= render "form", meal: @meal %>

  <%= link_to 'Back to meals', meals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/meals/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @meal %>

    <%= link_to 'Edit this meal', edit_meal_path(@meal), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this meal', meal_path(@meal), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to meals', meals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>
<%= render "ingredients_table" %>