config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  concern :searchable do
    post 'search_entries/index'
  end

  post 'search_entries/index'
  resources :shopping_lists
  resources :food_consumption_events, except: :show
  resources :meal_consumption_events, except: :show
  devise_for :users
  resources :meals do
    resources :ingredients
  end
  namespace :foods do
    concerns :searchable
  end

  post "foods/filter", to: 'foods#filter', as: "foods_filter"
  post "meals/filter", to: 'meals#filter', as: "meals_filter"
  namespace :meals do
    concerns :searchable
  end
  resources :foods
  get 'user_targets', to: 'user_targets#show', as: :user_targets
  patch 'user_targets', to: 'user_targets#update'
  get 'user_targets/edit', to: 'user_targets#edit', as: :edit_user_targets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'daily_log#index', as: :daily_log
end

app/models/food.rb
# frozen_string_literal: true
class Food < ApplicationRecord

  include Edible
  include Searchable

end

app/controllers/foods/search_entries_controller.rb
# frozen_string_literal: true

module Foods
  class SearchEntriesController < SearchEntriesController

    private

    def query
      super.search_only_in_model(Food)
    end

  end
end

app/controllers/foods_controller.rb
# frozen_string_literal: true
class FoodsController < ApplicationController

  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all.order('created_at desc')
  end

  def filter
    query = SearchQuery.new(params[:search])
    query.search_only_in_model(Food)
    search = Search::PerformSearchCommand.perform(search_query: query)
    @foods = if search.success?
              Food.where(id: search.value!.select(:searchable_id))
            else
              Food.all.order('created_at desc')
            end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
                 "foods", partial: "foods/foods", locals: {foods: @foods }
               )
      end
    end
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        Search::CreateSearchEntryCommand.perform(searchable_object: @food)
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        Search::UpdateSearchEntryCommand.perform(searchable_object: @food)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:fat, :carbs, :fibre, :protein, :calories, :name)
  end

end

app/helpers/foods_helper.rb
# frozen_string_literal: true
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= food.name %>
  </p>

  <%= render "meals/macros", meal: food %>

  <% if action_name != "show" %>
    <%= link_to "Show this food", food, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this food', edit_food_path(food), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/foods/_food_row.html.erb
<td class="px-7">
  <%= food.name %>
</td>

<td class="px-7">
  <%= food.fat %>
</td>

<td class="px-7">
  <%= food.carbs %>
</td>

<td class="px-7">
  <%= food.fibre %>
</td>

<td class="px-7">
  <%= food.protein %>
</td>

<td class="px-7">
  <%= food.calories %>
</td>

<td>
  <%= link_to 'Edit', edit_food_path(food), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
</td>

app/views/foods/_foods.html.erb
  <div id="foods" class="min-w-full">
    <%= render foods %>
  </div>

app/views/foods/_form.html.erb
<%= form_with(model: food, url: user_targets_path, method: :patch, class: "contents") do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :fat %>
    <%= form.text_field :fat, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :carbs %>
    <%= form.text_field :carbs, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fibre %>
    <%= form.text_field :fibre, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :protein %>
    <%= form.text_field :protein, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :calories %>
    <%= form.text_field :calories, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing food</h1>

  <%= render "form", food: @food %>

  <%= link_to "Show this food", @food, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to foods", foods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/foods/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Foods</h1>
    <%= link_to 'New food', new_food_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
    <%= turbo_frame_tag "foods_filter" do %>
    <%= form_with url: foods_filter_url do |form| %>
      <%= form.text_field :search %>
      <%= form.button("Search") %>
    <% end %>
      <%= render "foods", foods: @foods %>
    <% end %>
</div>

app/views/foods/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New food</h1>

  <%= render "form", food: @food %>

  <%= link_to 'Back to foods', foods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/foods/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @food %>

    <%= link_to 'Edit this food', edit_food_path(@food), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this food', food_path(@food), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to foods', foods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>