config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  concern :searchable do
    post 'search_entries/index'
  end

  post 'search_entries/index'
  resources :shopping_lists
  resources :food_consumption_events, except: :show
  resources :meal_consumption_events, except: :show
  devise_for :users
  resources :meals do
    resources :ingredients
  end
  namespace :foods do
    concerns :searchable
  end

  post "foods/filter", to: 'foods#filter', as: "foods_filter"
  post "meals/filter", to: 'meals#filter', as: "meals_filter"
  namespace :meals do
    concerns :searchable
  end
  resources :foods
  get 'user_targets', to: 'user_targets#show', as: :user_targets
  patch 'user_targets', to: 'user_targets#update'
  get 'user_targets/edit', to: 'user_targets#edit', as: :edit_user_targets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'daily_log#index', as: :daily_log
end

app/models/food_consumption_event.rb
# frozen_string_literal: true
class FoodConsumptionEvent < ApplicationRecord

  include Edible
  include Consumable

  belongs_to :user
  belongs_to :food

  %i[fat fibre carbs protein calories].each do |macro|
    define_method(macro) do
      food.send(macro) * (grams / 100.0)
    end
  end

end

app/controllers/food_consumption_events_controller.rb
# frozen_string_literal: true
class FoodConsumptionEventsController < ApplicationController

  before_action :set_food_consumption_event, only: %i[show edit update destroy]

  # GET /food_consumption_events or /food_consumption_events.json
  def index
    @food_consumption_events = FoodConsumptionEvent.all
  end

  # GET /food_consumption_events/new
  def new
    @food_consumption_event = FoodConsumptionEvent.new
  end

  # GET /food_consumption_events/1/edit
  def edit; end

  # POST /food_consumption_events or /food_consumption_events.json
  def create
    @food_consumption_event = new_or_existing_consumption_event
    @food_consumption_event.grams = @food_consumption_event.grams.to_f + food_consumption_event_params[:grams].to_f
    broadcast = broadcast_for(@food_consumption_event)
    respond_to do |format|
      if @food_consumption_event.save
        broadcast.perform(food_consumption_event: @food_consumption_event)
        format.turbo_stream { head :created }
        format.html do
          redirect_to food_consumption_event_url(@food_consumption_event),
                      notice: 'Food consumption event was successfully created.'
        end
        format.json { render :show, status: :created, location: @food_consumption_event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food_consumption_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_consumption_events/1 or /food_consumption_events/1.json
  def update
    respond_to do |format|
      if @food_consumption_event.update(food_consumption_event_params)
        Broadcasts::UpdateFoodConsumptionEvent.perform(@food_consumption_event)
        format.html do
          redirect_to food_consumption_event_url(@food_consumption_event),
                      notice: 'Food consumption event was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @food_consumption_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food_consumption_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_consumption_events/1 or /food_consumption_events/1.json
  def destroy
    @food_consumption_event.destroy

    respond_to do |format|
      format.html do
        redirect_to food_consumption_events_url, notice: 'Food consumption event was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food_consumption_event
    @food_consumption_event = FoodConsumptionEvent.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_consumption_event_params
    params.require(:food_consumption_event).permit(:food_id, :grams)
  end

  def new_or_existing_consumption_event
    food_id = food_consumption_event_params[:food_id]
    current_user
      .todays_food
      .where(food_id: food_id)
      .take || FoodConsumptionEvent.new(user: current_user, food_id: food_id)
  end

  def broadcast_for(food_consumption_event)
    food_consumption_event.new_record? ? Broadcasts::CreateFoodConsumptionEvent : Broadcasts::UpdateFoodConsumptionEvent
  end

end

app/helpers/food_consumption_events_helper.rb
# frozen_string_literal: true
module FoodConsumptionEventsHelper
end

app/views/food_consumption_events/_food_consumption_event.html.erb
<tr>
<div id="<%= dom_id food_consumption_event %>">
<% present(food_consumption_event) do |food| %>
  <td class="px-7">
    <%= food.name %>
  </td>

  <td class="px-7">
    <%= food.grams %>
  </td>

  <td class="px-7">
    <%= food.fat %>
  </td>

  <td class="px-7">
    <%= food.carbs %>
  </td>

  <td class="px-7">
    <%= food.fibre %>
  </td>

  <td class="px-7">
    <%= food.protein %>
  </td>

  <td class="px-7">
    <%= food.calories %>
  </td>
<% end %>
</div>
</tr>

app/views/food_consumption_events/_form.html.erb
<%= form_with(model: food_consumption_event, class: "contents") do |form| %>
  <% if food_consumption_event.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(food_consumption_event.errors.count, "error") %> prohibited this food_consumption_event from being saved:</h2>

      <ul>
        <% food_consumption_event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :grams %>
    <%= form.text_field :grams, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/food_consumption_events/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= "Editing consumption event for #{@food_consumption_event.food.name}" %></h1>

  <%= render "form", food_consumption_event: @food_consumption_event %>

  <%= link_to "Back to food consumption events", food_consumption_events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/food_consumption_events/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Food consumption events</h1>
    <%= link_to 'New food consumption event', new_food_consumption_event_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="food_consumption_events" class="min-w-full">
    <%= render @food_consumption_events %>
  </div>
</div>

app/views/food_consumption_events/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New food consumption event</h1>

  <%= render "form", food_consumption_event: @food_consumption_event %>

  <%= link_to 'Back to food consumption events', food_consumption_events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/food_consumption_events/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @food_consumption_event %>

    <%= link_to 'Edit this food_consumption_event', edit_food_consumption_event_path(@food_consumption_event), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this food_consumption_event', food_consumption_event_path(@food_consumption_event), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to food_consumption_events', food_consumption_events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>